-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS impactos.tb_descricao_acesso_agua
(
    codigo smallint NOT NULL,
    codigo_alpha character varying(120) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tb_descricao_acesso_agua_pkey PRIMARY KEY (codigo),
    CONSTRAINT tb_descricao_acesso_agua_codigo_alpha_key UNIQUE (codigo_alpha),
    CONSTRAINT tb_descricao_acesso_agua_descricao_key UNIQUE (descricao)
);

CREATE TABLE IF NOT EXISTS impactos.tb_descricao_cultura
(
    codigo smallint NOT NULL,
    codigo_alpha character varying(120) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tb_descricao_cultura_pkey PRIMARY KEY (codigo),
    CONSTRAINT tb_descricao_cultura_codigo_alpha_key UNIQUE (codigo_alpha),
    CONSTRAINT tb_descricao_cultura_descricao_key UNIQUE (descricao)
);

CREATE TABLE IF NOT EXISTS impactos.tb_descricao_de_chuva
(
    codigo smallint NOT NULL,
    codigo_alpha character varying(120) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tb_descricao_de_chuva_pkey PRIMARY KEY (codigo),
    CONSTRAINT tb_descricao_de_chuva_codigo_alpha_key UNIQUE (codigo_alpha),
    CONSTRAINT tb_descricao_de_chuva_descricao_key UNIQUE (descricao)
);

CREATE TABLE IF NOT EXISTS impactos.tb_descricao_dt_chuva
(
    codigo smallint NOT NULL,
    codigo_alpha character varying(120) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tb_descricao_dt_chuva_pkey PRIMARY KEY (codigo),
    CONSTRAINT tb_descricao_dt_chuva_codigo_alpha_key UNIQUE (codigo_alpha),
    CONSTRAINT tb_descricao_dt_chuva_descricao_key UNIQUE (descricao)
);

CREATE TABLE IF NOT EXISTS impactos.tb_descricao_impactos_agropecuaria
(
    codigo smallint NOT NULL,
    codigo_alpha character varying(120) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tb_descricao_impactos_agropecuaria_pkey PRIMARY KEY (codigo),
    CONSTRAINT tb_descricao_impactos_agropecuaria_codigo_alpha_key UNIQUE (codigo_alpha),
    CONSTRAINT tb_descricao_impactos_agropecuaria_descricao_key UNIQUE (descricao)
);

CREATE TABLE IF NOT EXISTS impactos.tb_descricao_percepcao_seca
(
    codigo smallint NOT NULL,
    codigo_alpha character varying(120) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tb_descricao_percepcao_seca_pkey PRIMARY KEY (codigo),
    CONSTRAINT tb_descricao_percepcao_seca_codigo_alpha_key UNIQUE (codigo_alpha),
    CONSTRAINT tb_descricao_percepcao_seca_descricao_key UNIQUE (descricao)
);

CREATE TABLE IF NOT EXISTS impactos.tb_descricao_qnt_chuva
(
    codigo smallint NOT NULL,
    codigo_alpha character varying(120) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tb_descricao_qnt_chuva_pkey PRIMARY KEY (codigo),
    CONSTRAINT tb_descricao_qnt_chuva_codigo_alpha_key UNIQUE (codigo_alpha),
    CONSTRAINT tb_descricao_qnt_chuva_descricao_key UNIQUE (descricao)
);

CREATE TABLE IF NOT EXISTS impactos.tb_descricao_restricoes_agua
(
    codigo smallint NOT NULL,
    codigo_alpha character varying(120) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tb_descricao_restricoes_agua_pkey PRIMARY KEY (codigo),
    CONSTRAINT tb_descricao_restricoes_agua_codigo_alpha_key UNIQUE (codigo_alpha),
    CONSTRAINT tb_descricao_restricoes_agua_descricao_key UNIQUE (descricao)
);

CREATE TABLE IF NOT EXISTS impactos.tb_descricao_sit_cultura
(
    codigo smallint NOT NULL,
    codigo_alpha character varying(120) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tb_descricao_sit_cultura_pkey PRIMARY KEY (codigo),
    CONSTRAINT tb_descricao_sit_cultura_codigo_alpha_key UNIQUE (codigo_alpha),
    CONSTRAINT tb_descricao_sit_cultura_descricao_key UNIQUE (descricao)
);

CREATE TABLE IF NOT EXISTS impactos.tb_impactos_seca
(
    codigo bigserial NOT NULL,
    municipio_codigo integer NOT NULL,
    data_referencia date NOT NULL,
    data_insercao timestamp without time zone DEFAULT now(),
    CONSTRAINT tb_impactos_seca_pkey PRIMARY KEY (codigo),
    CONSTRAINT uq_impacto_municipio_data UNIQUE (municipio_codigo, data_referencia)
);

CREATE TABLE IF NOT EXISTS impactos.tb_registro
(
    codigo bigserial NOT NULL,
    impacto_codigo bigint NOT NULL,
    percepcao_seca smallint,
    qnt_chuva smallint,
    dt_chuva smallint,
    de_chuva smallint,
    sit_cultura smallint,
    acesso_agua smallint,
    observacao text COLLATE pg_catalog."default",
    qualidade_dados smallint NOT NULL,
    criado_em timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT tb_registro_pkey PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS impactos.tb_registro_cultura
(
    codigo bigserial NOT NULL,
    registro_codigo bigint NOT NULL,
    cultura_codigo smallint NOT NULL,
    CONSTRAINT tb_registro_cultura_pkey PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS impactos.tb_registro_impacto_atividade
(
    codigo bigserial NOT NULL,
    registro_codigo bigint NOT NULL,
    impacto_codigo smallint NOT NULL,
    CONSTRAINT tb_registro_impacto_atividade_pkey PRIMARY KEY (codigo),
    CONSTRAINT tb_registro_impacto_atividade_registro_codigo_impacto_codig_key UNIQUE (registro_codigo, impacto_codigo)
);

CREATE TABLE IF NOT EXISTS impactos.tb_registro_outras_culturas
(
    codigo bigserial NOT NULL,
    registro_codigo bigint NOT NULL,
    descricao text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tb_registro_outras_culturas_pkey PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS impactos.tb_registro_qualidade
(
    codigo bigserial NOT NULL,
    descricao character varying(120) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tb_registro_qualidade_pkey PRIMARY KEY (codigo),
    CONSTRAINT tb_registro_qualidade_descricao_key UNIQUE (descricao)
);

CREATE TABLE IF NOT EXISTS impactos.tb_registro_restricao_agua
(
    codigo bigserial NOT NULL,
    registro_codigo bigint NOT NULL,
    restricao_codigo smallint NOT NULL,
    CONSTRAINT tb_registro_restricao_agua_pkey PRIMARY KEY (codigo),
    CONSTRAINT tb_registro_restricao_agua_registro_codigo_restricao_codigo_key UNIQUE (registro_codigo, restricao_codigo)
);

ALTER TABLE IF EXISTS impactos.tb_registro
    ADD CONSTRAINT tb_registro_acesso_agua_fkey FOREIGN KEY (acesso_agua)
    REFERENCES impactos.tb_descricao_acesso_agua (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS impactos.tb_registro
    ADD CONSTRAINT tb_registro_de_chuva_fkey FOREIGN KEY (de_chuva)
    REFERENCES impactos.tb_descricao_de_chuva (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS impactos.tb_registro
    ADD CONSTRAINT tb_registro_dt_chuva_fkey FOREIGN KEY (dt_chuva)
    REFERENCES impactos.tb_descricao_dt_chuva (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS impactos.tb_registro
    ADD CONSTRAINT tb_registro_impacto_codigo_fkey FOREIGN KEY (impacto_codigo)
    REFERENCES impactos.tb_impactos_seca (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS impactos.tb_registro
    ADD CONSTRAINT tb_registro_percepcao_seca_fkey FOREIGN KEY (percepcao_seca)
    REFERENCES impactos.tb_descricao_percepcao_seca (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS impactos.tb_registro
    ADD CONSTRAINT tb_registro_qnt_chuva_fkey FOREIGN KEY (qnt_chuva)
    REFERENCES impactos.tb_descricao_qnt_chuva (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS impactos.tb_registro
    ADD CONSTRAINT tb_registro_qualidade_dados_fkey FOREIGN KEY (qualidade_dados)
    REFERENCES impactos.tb_registro_qualidade (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS impactos.tb_registro
    ADD CONSTRAINT tb_registro_sit_cultura_fkey FOREIGN KEY (sit_cultura)
    REFERENCES impactos.tb_descricao_sit_cultura (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS impactos.tb_registro_cultura
    ADD CONSTRAINT tb_registro_cultura_cultura_codigo_fkey FOREIGN KEY (cultura_codigo)
    REFERENCES impactos.tb_descricao_cultura (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS impactos.tb_registro_cultura
    ADD CONSTRAINT tb_registro_cultura_registro_codigo_fkey FOREIGN KEY (registro_codigo)
    REFERENCES impactos.tb_registro (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS impactos.tb_registro_impacto_atividade
    ADD CONSTRAINT tb_registro_impacto_atividade_impacto_codigo_fkey FOREIGN KEY (impacto_codigo)
    REFERENCES impactos.tb_descricao_impactos_agropecuaria (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS impactos.tb_registro_impacto_atividade
    ADD CONSTRAINT tb_registro_impacto_atividade_registro_codigo_fkey FOREIGN KEY (registro_codigo)
    REFERENCES impactos.tb_registro (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS impactos.tb_registro_outras_culturas
    ADD CONSTRAINT tb_registro_outras_culturas_registro_codigo_fkey FOREIGN KEY (registro_codigo)
    REFERENCES impactos.tb_registro (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS impactos.tb_registro_restricao_agua
    ADD CONSTRAINT tb_registro_restricao_agua_registro_codigo_fkey FOREIGN KEY (registro_codigo)
    REFERENCES impactos.tb_registro (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS impactos.tb_registro_restricao_agua
    ADD CONSTRAINT tb_registro_restricao_agua_restricao_codigo_fkey FOREIGN KEY (restricao_codigo)
    REFERENCES impactos.tb_descricao_restricoes_agua (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;
